# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/pharmacy_db
spring.datasource.username=root
spring.datasource.password=root123
# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger/OpenAPI (for Sprint 2 Review validation)
springdoc.swagger-ui.path=/swagger-ui.html